from comms.trainings.federated.main import train_and_validate_federated
from comms.trainings.federated.apfl import train_and_validate_federated_apfl
from comms.trainings.federated.drfa import train_and_validate_federated_drfa
from comms.trainings.federated.afl import train_and_validate_federated_afl

from comms.trainings.federated.centered.main import train_and_validate_federated_centered
from comms.trainings.federated.centered.apfl import train_and_validate_apfl_centered
from comms.trainings.federated.centered.drfa import train_and_validate_drfa_centered
from comms.trainings.federated.centered.afl import train_and_validate_afl_centered
from comms.trainings.federated.centered.perfedme import train_and_validate_perfedme_centered